"""empty message

Revision ID: 28953a6d0cb6
Revises: d5db04a26bda
Create Date: 2026-05-12 16:54:12.901886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28953a6d0cb6'
down_revision = 'd5db04a26bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('color')

    with op.batch_alter_table('jote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
